sudo: required
dist: xenial

language:
  - cpp

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - # cmake/boost versions:
  - CMAKE_V=3.14.5
  - CMAKE_SV=${CMAKE_V::-2}
  - BOOST_V=1.70.0
  - # Get and install cmake:
  - wget https://cmake.org/files/v${CMAKE_SV}/cmake-${CMAKE_V}.tar.gz
  - tar xf cmake-${CMAKE_V}.tar.gz
  - cd cmake-${CMAKE_V}
  - ./configure
  - make
  - sudo make install
  - cd ..
  - # Get and install boost:
  - PROJECT_DIR=`pwd`
  - BOOST=$HOME/boost
  - git clone --depth 1 -b boost-$BOOST_V https://github.com/boostorg/boost.git $BOOST
  - cd $BOOST
  - git submodule update --init --merge
  - ./bootstrap.sh
  - ./b2 headers
  - cd $PROJECT_DIR
  - export BOOST_ROOT=$BOOST

script:
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD} -DCJ_TEST=ON -DBOOST_ROOT="$BOOST"
  - make && ./test/test_cj
